### ISSUE TITLE
Historia #23 - Ver los autores a los que está suscrito

### ISSUE THREAD

**Issue by GuiselleZP** [IngenioUN/back_end#52]
- Ver los autores a las que el usuario logueado está suscrito (Ver notificaciones)
- Ver los autores a las que otro usuario está suscrito

**Comment by jjpb44** [comment]
Devolver la lista de autores a los que sigue el usuario u otro autor.

**Comment by jjpb44** [comment]
Return just the subscribed authors from the params id
