### ISSUE TITLE
Implementar Logger

### ISSUE THREAD

**Issue by jujpenabe** [IngenioUN/back_end#6]
Crear archivo .log que registre las acciones.

**Comment by jjpb44** [comment]
Add log levels with morgan

**Comment by GuiselleZP** [comment]
Agregar las llamadas al lloger en el back-end

**Comment by GuiselleZP** [comment]
Resolver el problema de escritura sobre el archivo .log

**Comment by jjpb44** [comment]
debug level is not showing: change levels in logger.js

**Comment by jjpb44** [comment]
Simple console view
